name: speakglobeai
description: "SpeakGlobeAI - A Multi-modal AI tool for Voice, Image, and Document translation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:

  flutter:
    sdk: flutter
  
  # Firebase Core & Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.0

  # Feature 1: STT & TTS (Voice Assistant)
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.5
  translator: ^1.0.0

# Feature 2: Image Analyzer (ML Kit) - Versions Aligned
  image_picker: ^1.2.1
  google_mlkit_image_labeling: ^0.12.0
  google_mlkit_text_recognition: ^0.13.0  # Downgraded for compatibility
  google_mlkit_translation: ^0.11.0

  # Feature 3: Document Converter
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^21.1.35
  path_provider: ^2.1.1

  # grammer Function
  google_generative_ai: ^0.4.0

  # UI & Utilities
  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true